- name: Install/Update kitty and optional libraries
  tags:
    - kitty
  block:
    - name: install kitty
      pacman:
        name:
          - kitty
          - kitty-shell-integration
          - kitty-terminfo
        state: latest
      become: yes
      tags:
        - install

    - name: create kitty config folder
      file:
        path: ~/.config/kitty
        state: directory
      tags:
        - config

    - name: Install kitty config
      copy:
        src: ./configs/kitty/
        dest: ~/.config/kitty/
      tags:
        - config

