- name: Install/Update kitty and optional libraries
  pacman:
    name:
      - kitty
      - kitty-shell-integration
      - kitty-terminfo
    state: latest
  become: yes

- name: Create kitty config directory
  file:
    path: ~/.config/kitty
    state: directory

- name: Install kitty config
  copy:
    src: ./configs/kitty/
    dest: ~/.config/kitty/

