  - name: Print Qutebrowser installation
    debug:
      msg: Install Qutebrowser
  - name: Copy Config to destination
    copy:
      src: ./configs/qutebrowser
      dest: ~/.config/qutebrowser
  - name: Install/Update Qutebrowser and optional libraries
    pacman:
      name:
        - qutebrowser
        - python-adblock
        - python-pygments
      state: latest
