- name: nvim configuration
  tags:
    - nvim
  block:
  - name: Create nvim config directory
    file:
      path: ~/.config/nvim
      state: directory
    tags:
      - config

  - name: Install nvim lua folder
    copy:
      src: ./configs/nvim/lua/
      dest: ~/.config/nvim/lua/
    tags:
      - config

  - name: Install nvim init
    copy:
      src: ./configs/nvim/init.lua
      dest: ~/.config/nvim/init.lua
    tags:
      - config

  - name: Install/Update nvim and optional libraries
    kewlfft.aur.aur:
      name: nvim-packer-git
      state: latest
    become: yes
    tags:
      - install

