- name: Install/Update Xorg and optional libraries
  pacman:
    name:
      - xorg
    state: latest
  tags: install, xorg

- name: copy XCompose
  copy:
    src: ./configs/xorg/.XCompose
    dest: ~/.XCompose
  tags: config, xorg

- name: copy Autostart
  copy:
    src: ./configs/xorg/autostart.sh
    dest: ~/.local/share/autostart.sh
  tags: xorg, config

# block for notebooks
- block:
  - name: copy config for mousepad
    copy:
      src: ./configs/xorg/70-synaptics.conf
      dest: ~/.config/X11/xorg.conf.d/70-synaptics.conf

  - name: Copy xinitrc to destination for Notebooks
    copy:
      src: ./configs/xorg/xinitrc_notebooks
      dest: ~/.xinitrc
  when: inventory_hostname in groups['notebooks'] 
  tags: xorg, config

# block for desktops
- block: 
  - name: Copy xinitrc to destination for desktop
    copy:
      src: ./configs/xorg/xinitrc_desktops
      dest: ~/.xinitrc
  when: inventory_hostname in groups['desktops'] 
  tags: xorg, config
