 - name: create polybar config directory
   file:
     path: ~/.config/polybar
     state: directory

 - name: Install polybar config
   copy:
     src: ./configs/polybar/config.ini
     dest: ~/.config/polybar/config.ini

 - name: Install polybar launch script
   copy:
     src: ./configs/polybar/launch.sh
     dest: ~/.config/polybar/launch.sh
     mode: a+x

 - name: Install/Update polybar and optional libraries
   pacman:
     name:
       - polybar
     state: latest
